In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
import torch
import torch.nn as nn

In [2]:
sentence = "strength is the only hierarchy"

In [3]:
tokens = sentence.split(" ")

In [4]:
word_2int = {word: i for i, word in enumerate(tokens)}

In [5]:
sequence = [word_2int[token] for token in tokens]

In [6]:
sequence

[0, 1, 2, 3, 4]

In [7]:
n, d= 5, 5
embedding = nn.Embedding(n, d, max_norm=True)
idx = torch.tensor(sequence)
b = embedding(idx)

In [8]:
b = b.detach()

In [9]:
embeds = b.clone().detach()

In [10]:
b[0]

tensor([ 0.1196, -0.7460,  0.1474,  0.5925, -0.2376])

In [11]:
np.dot(b[0].T , embeds[1])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2318.)
  """Entry point for launching an IPython kernel.


-0.0031811018

In [12]:
ai = []
for i, x in enumerate(b):
    arr = []
    for j, y in enumerate(embeds):
        arr.append(np.dot(x.T, y))
    ai.append(arr)

In [13]:
ai

[[0.9999999, -0.0031811018, 0.17912538, 0.56732464, -0.5504806],
 [-0.0031811018, 0.9999999, 0.61803585, 0.40151975, 0.26140693],
 [0.17912538, 0.61803585, 0.99999994, 0.1182069, 0.61695135],
 [0.56732464, 0.40151975, 0.1182069, 0.9999998, -0.58394384],
 [-0.5504806, 0.26140693, 0.61695135, -0.58394384, 0.99999994]]

In [14]:
ai = np.array(ai)

In [15]:
ai = np.exp(ai)/np.exp(ai).sum(axis=1)[:,None]

In [16]:
ai

array([[0.3748583 , 0.13746467, 0.16495514, 0.24319722, 0.07952468],
       [0.11919118, 0.32502753, 0.22183764, 0.1786502 , 0.1552935 ],
       [0.13672899, 0.21206889, 0.31071475, 0.1286483 , 0.21183902],
       [0.23025487, 0.1950746 , 0.14694661, 0.35490924, 0.07281474],
       [0.08232682, 0.18541276, 0.2645761 , 0.07961749, 0.38806686]],
      dtype=float32)

In [17]:
np.sum(ai[1])

1.0

In [18]:
A = np.matmul(ai, embeds)

In [19]:
A

tensor([[ 0.1029, -0.5849,  0.1425, -0.0263, -0.1859],
        [ 0.0716, -0.4334,  0.0548, -0.3886, -0.2697],
        [ 0.0051, -0.4284, -0.0788, -0.3810, -0.2749],
        [ 0.1323, -0.5606,  0.2225, -0.1432, -0.1487],
        [-0.0900, -0.2954, -0.2105, -0.4822, -0.2855]])