<a href="https://colab.research.google.com/github/silvererudite/30-for-30-ml-projects/blob/main/pandas_numpy_snippets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_arr = np.array([[1,2,3], [4,5,6]])
# generate array from random data
data_rand = np.random.randn(2,3)

In [3]:
print(data_arr)
print(data_rand)
print(data_arr.shape)
print(data_rand.shape)

[[1 2 3]
 [4 5 6]]
[[-0.15843926  0.27376892  0.50669389]
 [ 0.65258402 -0.16634955 -1.56879309]]
(2, 3)
(2, 3)


In [4]:
data_arr.dtype

dtype('int64')

# Indexing and slicing numpy arrays

In [5]:
# 1D array
arr = np.arange(10)
arr[4:8]

array([4, 5, 6, 7])

In [6]:
arr[4:8] = 10 # the assignment is broadcasted to the entire array
arr

array([ 0,  1,  2,  3, 10, 10, 10, 10,  8,  9])

## Array slices are views on the original array and the original array is not copied. 
This increases efficiency, but changes will be reflected on the original array

In [7]:
arr_slice = arr[0:3]
arr_slice

array([0, 1, 2])

In [8]:
arr_slice[1] = 50
arr

array([ 0, 50,  2,  3, 10, 10, 10, 10,  8,  9])

`[:]` all rows and columns
ommitting the later indices in multidim array returns ndarray

# Multidim array

In [10]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])