<a href="https://colab.research.google.com/github/silvererudite/30-for-30-ml-projects/blob/main/pytorch-tuts/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


# Tensors
## Creating Tensors

In [31]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [32]:
scalar.ndim

0

Getting back the data

In [33]:
scalar.item()

6

In [34]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [35]:
print(vector.shape)
print(vector.ndim)

torch.Size([2])
1


In [36]:
MATRIX = torch.tensor([[1,2,3], [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
print(MATRIX.shape)
print(MATRIX.ndim)

torch.Size([2, 3])
2


In [38]:
TENSOR = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])
print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([1, 3, 3])
3


### Random tensors

In [39]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.2504, 0.6630, 0.2956],
        [0.4229, 0.9556, 0.0612]])

In [40]:
rand_img_tensor = torch.rand((224, 224, 3))
print(rand_img_tensor.shape)
print(rand_img_tensor.ndim)

torch.Size([224, 224, 3])
3


### Zeros / Ones tensors

In [41]:
zeros = torch.zeros((3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [42]:
ones = torch.ones((3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

# Range tensors and tensors-like

In [43]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
tensors_like = torch.zeros_like(one_to_ten)
tensors_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor dTypes

In [45]:
float_32_ten = torch.tensor([3.0,4.0,5.9], dtype=torch.float32, device=None, requires_grad =False)
float_32_ten

tensor([3.0000, 4.0000, 5.9000])

In [46]:
float_16_ten = float_32_ten.type(torch.float16)
float_16_ten

tensor([3.0000, 4.0000, 5.8984], dtype=torch.float16)

In [47]:
float_16_ten * float_32_ten

tensor([ 9.0000, 16.0000, 34.8008])

In [48]:
tensors_like.dtype

torch.int64

## Tensor Operatons

In [49]:
# tensor + 10 torch.add(tensor, 10)
# tensor * 10
# tensor - 10
# torch.mul(tensor, 10)

## Matrix multiplication

1. Element-wise 
2. Mat mult or dot product




In [50]:
# tensor * tensor
# torch.matmul() / torch.mm()
# fixing tensor shapes
# tensor.T