<a href="https://colab.research.google.com/github/silvererudite/30-for-30-ml-projects/blob/main/pytorch-tuts/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


# Tensors
## Creating Tensors

In [ ]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [ ]:
scalar.ndim

0

Getting back the data

In [ ]:
scalar.item()

6

In [ ]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
print(vector.shape)
print(vector.ndim)

torch.Size([2])
1


In [ ]:
MATRIX = torch.tensor([[1,2,3], [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print(MATRIX.shape)
print(MATRIX.ndim)

torch.Size([2, 3])
2


In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])
print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([1, 3, 3])
3


### Random tensors

In [ ]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332]])

In [ ]:
rand_img_tensor = torch.rand((224, 224, 3))
print(rand_img_tensor.shape)
print(rand_img_tensor.ndim)

torch.Size([224, 224, 3])
3


### Zeros / Ones tensors

In [ ]:
zeros = torch.zeros((3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
ones = torch.ones((3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

# Range tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tensors_like = torch.zeros_like(one_to_ten)
tensors_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor dTypes

In [ ]:
float_32_ten = torch.tensor([3.0,4.0,5.9], dtype=torch.float32, device=None, requires_grad =False)
float_32_ten

tensor([3.0000, 4.0000, 5.9000])

In [ ]:
float_16_ten = float_32_ten.type(torch.float16)
float_16_ten

tensor([3.0000, 4.0000, 5.8984], dtype=torch.float16)

In [ ]:
float_16_ten * float_32_ten

tensor([ 9.0000, 16.0000, 34.8008])

In [ ]:
tensors_like.dtype

torch.int64

## Tensor Operatons

In [ ]:
# tensor + 10 torch.add(tensor, 10)
# tensor * 10
# tensor - 10
# torch.mul(tensor, 10)

## Matrix multiplication

1. Element-wise 
2. Mat mult or dot product




In [ ]:
# tensor * tensor
# torch.matmul() / torch.mm()
# fixing tensor shapes
# tensor.T

### Mean requires dtype in `float`

In [ ]:
t = torch.tensor([1,2,3,4])
torch.mean(t.type(torch.float16))

tensor(2.5000, dtype=torch.float16)

In [ ]:
print(torch.argmax(t.type(torch.float16)))
print(torch.argmin(t.type(torch.float16)))

tensor(3)
tensor(0)


## Reshaping, stacking, viewing, squeezing and unsqueezing
- Reshape - reshapes an input tensor in a defined shape
- View -  returns a different perspective of the tensor but shares the same memory with the original tensor
- Stacking - vertical stacking or horizontal stacking
- Squeeze -  removes all `1` dimension from tensor
- Unsqueeze - adds a `1` dimension to tensor
- Permute -  returns a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [ ]:
z = x.view(3,3)
z[0, 0] = 16
z, x

(tensor([[16.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]]),
 tensor([16.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[16., 16., 16., 16.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [ ]:
x_squeeze = torch.squeeze(x.reshape(1,9))
x_squeeze

tensor([16.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [ ]:
x.reshape(1, 9).shape, x_squeeze.shape

(torch.Size([1, 9]), torch.Size([9]))

In [ ]:
y = torch.arange(1, 10).reshape(1, 3, 3)
y, y.shape, y.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]), 3)

In [ ]:
y[0][0][0]

tensor(1)

In [ ]:
y[:,:,2]

tensor([[3, 6, 9]])

## Pytorch and Numpy
`torch.from_numpy(array)`
`torch.Tensor.numpy()`

## Reproducibilty
Making random numbers not so random to reproduce code


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)


# Workflow

In [ ]:
from torch import nn
import matplotlib.pyplot as plt

## Data preparating and loading

In [ ]:
weight = 0.7
bias = 0.3

start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias
X , y

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800],
         [0.2000],
         [0.2200],
         [0.2400],
         [0.2600],
         [0.2800],
         [0.3000],
         [0.3200],
         [0.3400],
         [0.3600],
         [0.3800],
         [0.4000],
         [0.4200],
         [0.4400],
         [0.4600],
         [0.4800],
         [0.5000],
         [0.5200],
         [0.5400],
         [0.5600],
         [0.5800],
         [0.6000],
         [0.6200],
         [0.6400],
         [0.6600],
         [0.6800],
         [0.7000],
         [0.7200],
         [0.7400],
         [0.7600],
         [0.7800],
         [0.8000],
         [0.8200],
         [0.8400],
         [0.8600],
         [0.8800],
         [0.9000],
         [0.9200],
         [0.9400],
         [0.9600],
         [0.9800]]), tensor([[0.3000],
         [0.3140],
         [0

In [ ]:
train_split = int(0.8 * len(X))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

## Creating a simple Pytorch model
create linear regression model class

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
    self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))

    # Forward method
  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias


In [ ]:
## Checking contents of model
torch.manual_seed(42)

model_0 = LinearRegressionModel()
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True), Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [ ]:
model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [ ]:
## Making predictions
with torch.inference_mode(): # faster than no_grad()
  y_preds = model_0(X_test)
y_preds

tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])

In [ ]:
## Training model
loss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(params=model_0.parameters(),lr = 0.01)

### Building a training loop
0. loop through data
1. Forward paa
2. Calculate loss
3. Optimize 
4. Loss backwards
5. Adjust model params

In [ ]:
epochs = 10
for epoch in range(epochs):
  model_0.train()

  y_pred = model_0(X_train)
  loss = loss_fn(y_pred, y_train)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()